import { StyleSheet } from "react-native";
const Styles = StyleSheet.create({
  container: {
    backgroundColor: "white",
    flex: 1,
  },
  img: {
    flex: 0.7,
    width: 378,
    height: 360,
  },
  icomic: {
    borderRadius: 100,
    backgroundColor: "#95a5ba",
    height: 50,
    width: 50,
    justifyContent: "center",
    alignItems: "center",
    left: 50,
    top: -99,
  },
  easy: {
    color: "#BFCDE0",
    fontSize: 36,
    fontWeight: "600",
    top: -150,
    fontFamily: "SofiaSans-VariableFont",
  },
  recorder: {
    color: "#3B3355",
    fontSize: 36,
    top: 115,
    fontFamily: "SofiaSans-VariableFont",
  },
  center: {
    alignSelf: "center",
    left: 30,
  },
  circle: {
    flexDirection: "row-reverse",
    marginTop: 50,
    marginLeft: 10,
  },
  qcinza: {
    flexDirection: "row",
    justifyContent: "space-around",
    height: 5,
    top: -110,
  },
  quadrado1: {
    backgroundColor: "#D9D9D9",
    flex: 0.2,
    borderRadius: 8,
    height: 120,
    left: -65,
  },
  quadrado2: {
    backgroundColor: "#D9D9D9",
    flex: 0.3,
    height: 120,
    borderRadius: 8,
    left: -50,
  },
  quadrado3: {
    backgroundColor: "#D9D9D9",
    flex: 0.3,
    height: 120,
    borderRadius: 8,
    left: -23,
  },
  quadrado4: {
    backgroundColor: "#D9D9D9",
    flex: 0.2,
    height: 120,
    borderRadius: 8,
  },
  qp: {
    flexDirection: "row",
    justifyContent: "space-around",
    height: 5,
    top: -120,
  },
  quad1: {
    width: 97,
    height: 107,
    top: 150,
    border: "1 solid",
    backgroundColor: "#fff",
    borderColor: "#5D5D81",
    borderRadius: 10,
    borderWidth: 1,
  },
  quad2: {
    height: 107,
    width: 97,
    top: 150,
    backgroundColor: "#fff",
    borderColor: "#5D5D81",
    borderRadius: 10,
    borderWidth: 1,
  },
  quad3: {
    width: 103,
    height: 113,
    top: 150,
    backgroundColor: "#fff",
    borderColor: "#3B3355",
    borderRadius: 10,
    borderWidth: 2,
  },
  text1: {
    color: "#5D5D81",
    fontFamily: "SofiaSans-VariableFont",
    fontSize: 30,
    alignSelf: "center",
    top: 15,
    fontWeight: "700",
  },
  t1: {
    color: "#5D5D81",
    alignSelf: "center",
    fontSize: 25,
    fontWeight: "400",
    top: 10,
    fontFamily: "SofiaSans-VariableFont",
  },
  text2: {
    color: "#5D5D81",
    fontFamily: "SofiaSans-VariableFont",
    fontSize: 30,
    alignSelf: "center",
    top: 15,
    fontWeight: "700",
  },
  t2: {
    color: "#5D5D81",
    alignSelf: "center",
    fontSize: 25,
    fontWeight: "400",
    top: 10,
    fontFamily: "SofiaSans-VariableFont",
  },
  text3: {
    color: "#918DA0",
    fontFamily: "SofiaSans-VariableFont",
    fontSize: 20,
    alignSelf: "center",
    top: 8,
  },
  text4: {
    color: "#3B3355",
    fontFamily: "SofiaSans-VariableFont",
    fontSize: 35,
    alignSelf: "center",
    fontWeight: "700",
    top: -2,
  },
  t3: {
    color: "#3B3355",
    alignSelf: "center",
    fontFamily: "SofiaSans-VariableFont",
    fontSize: 26,
    fontWeight: "500",
    top: -10,
  },
  linha: {
    backgroundColor: "#918DA0",
    width: 54.06,
    height: 2,
    left: 22,
    top: -6,
    transform: [{ rotateY: "1deg" }, { rotateZ: "15deg" }],
  },
  circulo: {
    flexDirection: "row",
    justifyContent: "space-around",
    top: 150,
  },
  c: {
    backgroundColor: "#fff",
    color: "#3B3355",
    borderWidth: 1,
    width: 14,
    height: 14,
    borderRadius: 10,
  },
  c3: {
    backgroundColor: "#3B3355",
    borderWidth: 1,
    width: 14,
    height: 14,
    borderRadius: 10,
  },
  cont: {
    justifyContent: "center",
    width: 351,
    top: 165,
    alignSelf: "center",
    borderRadius: 6,
  },
  t4: {
    color: "white",
    fontFamily: "SofiaSans-VariableFont",
    fontSize: 35,
    alignSelf: "center",
    fontWeight: "700",
  },
  textao: {
    color: "black",
    alignSelf: "center",
    lineHeight: 10,
    bottom: -170,
    width: 351,
    justifyContent: "center",
    fontFamily: "SofiaSans-VariableFont",
    fontWeight: "300",
    fontSize: 10,
    textAlign: "justify",
  },
  linearGradient: {
    flex: 3,
    opacity: 10,
    width: 378,
    height: 360,
  },
});
export default Styles;
